version: '3.8'
services:
  backend:
    build: ./pricingcomponent
    container_name: mm-gateway-backend
    ports:
      - "7070:7070"
    volumes:
      - ./logs:/app/logs
    # Tweak variables here for the end-user
    environment:
      - MIN_PROFIT_MARGIN=0.003
      - TICK_SIZE=0.001
    restart: unless-stopped

  frontend:
    build: ./frontend_streamlit
    container_name: mm-gateway-ui
    ports:
      - "8501:8501"
    environment:
      # This tells the python script to use the internal Docker DNS and port
      - BACKEND_ADDR=mm-gateway-backend:7070
    depends_on:
      - backend
    restart: unless-stopped
